[path]
data = "/Users/alextran99/Library/CloudStorage/OneDrive-HoustonMethodist/niceview-main_2/db/data/"
cache = "/Users/alextran99/Library/CloudStorage/OneDrive-HoustonMethodist/niceview-main_2/db/cache/"

[constant]
cmin = 0
cmax = 255
max_file_size = 5000
