[path]
db = '/home/tom/github/niceview/db/'
data = '/home/tom/github/niceview/db/data/'
cache = '/home/tom/github/niceview/db/cache/'
plot = '/home/tom/github/niceview/db/plot/'

[constant]
cmin = 0
cmax = 255
max_file_size = 5000